### ISSUE TITLE
What exactly is a function?

### ISSUE THREAD

**Issue by pchampin** [FnOio/fno-specification#1]
I'm having a hard time figuring out exactly what a *function* is, according to this ontology.

A *function* is defined to be "an actionable thing", but then it is described as "abstract" (as opposed to *implementations*, which are concrete). This seems a little contradictory. I guess that functions are rather "templates" or "prototypes" for actionable things?

I could live with that, but then I would consider that a *function* is akin to what I call a *problem* (i.e. an specified relation between a set of inputs and a set of outputs) or to what I call an *algorithm* (i.e. an abstract action plan to solve a given problem), depending on whether *how* the problem is solved is considered part of the function or not. But then the ontology defines both *problem* and *algorithm* classes, so obviously, *functions* are meant to be something else...

More specifically, in my own mental model, an *implementation* implements an *algorithm*, which in turn solves a *problem*. I don't really see the benefit brought by *functions*, which seem to stand somewhere in between *implementation* and *algorithm*...

I think the "sum" example is too simple to illustrate the benefit of each of the introduced concepts.

**Comment by bjdmeest** [comment]
We updated the spec and tried to clarify the difference between function, problem, and implementation. The biggest difference is that an implementation depends on a specific development context, whereas a function is an implementation-independent description (so, the JAVA sum implementation and JavaScript sum implementation could both be mapped to the same Function). A Problem is something more generic, something that is not always solvable by a single function.

Our attempt at improving the descriptions start at https://fno.io/spec/#dfn-function. However, if there's something unclear, feel free to let us know, we're happy to improve our documentation (but we had some tech debt accumulated, sorry for the late response in this case)

**Comment by pchampin** [comment]
Thanks for the clarifications; things are getting a bit clearer, but I still have issues:

* I still fail to see how functions can be both "abstract" and "actionable"? It seems to me that only a particular implementation of a functions is actually actionable.

* https://fno.io/spec/#dfn-function says that a function has parameters, but then that it is merely a function **declaration**. Shouldn't this be **description** instead?

* I am surprised that only functions have parameters. I would expect *algorithms* to also have parameters.

**Comment by bjdmeest** [comment]
- Well, we tried to hint at the fact that we can also describe the execution result of a function in an implementation-independent manner. But we could change that sentence into the more explicit `A function can have input parameters, output, solve certain problems, and can be implemented using certain algorithms. It's execution can also be described in an implementation-independent manner, see https://fno.io/spec/#dfn-execution`. Would that clarify things?
- Ah yes, indeed, the 'declaration' sentence comes too late, the start should rather be `A function is a process that performs a specific task. In essence, its identification is a function declaration. A function can associate one or more parameters to an output.`. We meant to say that, e.g., `ex:sum a fno:Function` is a declaration, when adding all parameters and outputs etc, it becomes a description (which is stated in https://fno.io/spec/#dfn-output).
- We should clarify that problem and algorithm are not described in detail within FnO. We mostly provide placeholder-like relations to point to other vocabularies or ontologies. So indeed, you could further specify algorithms, but we haven't encountered that need in our use cases (yet).

**Comment by pchampin** [comment]
> * Well, we tried to hint at the fact that we can also describe the execution result of a function in an implementation-independent manner. (...). Would that clarify things?

Yes

> * Ah yes, indeed, the 'declaration' sentence comes too late, (...)

Ok, it's clearer that way

> * We should clarify that problem and algorithm are not described in detail within FnO. (...)

That confirms a hint that I had, but making it more explicit would definitely help the reader.

**Comment by bjdmeest** [comment]
Updated by dc02d4098f97c5522f7c78f1206905e8a9539f68, thanks for the feedback!

**Comment by alexander-mart** [comment]
@pchampin Also related topic:
https://en.wikipedia.org/wiki/Function_(mathematics)
