### ISSUE TITLE
Illustrate the multiple cardinalities

### ISSUE THREAD

**Issue by pchampin** [FnOio/fno-specification#2]
The intro of section "3.1 Function (abstract)" states that a function can
* implement multiple algorithms,
* solve multiple problems.

This is not entirely clear to me; examples would definitely help (and would also probably help with #1).

**Comment by bjdmeest** [comment]
Could you have a look at https://fno.io/spec/#dfn-function and further to see whether it's more clear now? If not, feel free to let us know :)

**Comment by pchampin** [comment]
Sorry for leaving this open for so long. Yes, the new phrasing makes it clearer.
