### ISSUE TITLE
How is the Turtle file generated?

### ISSUE THREAD

**Issue by bblfish** [FnOio/fno-specification#9]
Where is the repository for the ontology being developed here?
The current doc points to 
https://w3id.org/function/ontology/1.0.0
which resolves to 
https://fno.io/ontology/1.0.0/ontology.ttl

Is that generated from the html somehow? Would be worth documenting if so.

**Comment by bjdmeest** [comment]
Added a link to https://github.com/IDLabResearch/function-ontology, where the ontology files are maintained
